name: Publish Docker image

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image:
        description: 'Image'
        required: true
        default: 'conformance-suite'
        type: choice
        options:
          - node-lts-chromium
          - conformance-suite
          - obb-certification

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: cache driver
        run: docker buildx create --use --driver=docker-container

      - name: Get date tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H')"

      - name: Build and push Docker image (node-lts-alpine.chromium)
        uses: docker/build-push-action@v4
        if: ${{ inputs.image == null || inputs.image == 'node-lts-chromium' }}
        continue-on-error: true
        with:
          context: .
          file: Node-lts+Chromium/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            adrielcodeco/node-lts-alpine.chromium:latest
            adrielcodeco/node-lts-alpine.chromium:${{ steps.date.outputs.date }}

      - name: Build and push Docker image (conformance-suite)
        uses: docker/build-push-action@v4
        if: ${{ inputs.image == null || inputs.image == 'conformance-suite' }}
        continue-on-error: true
        with:
          context: .
          file: conformance-suite/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            adrielcodeco/conformance-suite:latest
            adrielcodeco/conformance-suite:${{ steps.date.outputs.date }}

      - name: Build and push Docker image (obb-certification)
        uses: docker/build-push-action@v4
        if: ${{ inputs.image == null || inputs.image == 'obb-certification' }}
        continue-on-error: true
        with:
          context: .
          file: obb-certification/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            adrielcodeco/obb-certification:latest
            adrielcodeco/obb-certification:${{ steps.date.outputs.date }}
